### ISSUE TITLE
Missing or invalid shipment charge type

### ISSUE THREAD

**Issue by Eikzx** [ShipStream/ups-rest-php-sdk#14]
Hello,

The type is actually set  as you can see in the Screenshot appended.
It seems like the index "Type" is getting stripped away leading to the error or response:

"{"response":{"errors":[{"code":"9120067","message":"Missing or invalid shipment charge type."}]}}"

![Bildschirmfoto 2024-03-25 um 12 52 23](https://github.com/ShipStream/ups-rest-php-sdk/assets/149160420/ebc60342-6467-43b8-adca-22ad929c7c09)

We are using the the current release in this happens using the shipment API. Also the right Model is used (\ShipStream\Ups\Api\Model\PaymentInformationShipmentCharge) to set the shipmentCharge.

Kindest regards
Eike

**Comment by elidrissidev** [comment]
Hey there,

I tried to replicate this issue to no avail, in my case the request `ShipmentCharge` field is properly formatted. Are you using the Shipping or the Rating API? Can you share a short snippet of how you're calling the code?

**Comment by Eikzx** [comment]
Hello,

appended the code Snippet.
I am using the shipping API trying to create a shipment.
I commented the part where the actual ShipmentCharge object ist set as the setShipmentCharge expects an array and not the object.
Therefore, for testing Purposes I defined the Array myself.

![Bildschirmfoto 2024-03-25 um 13 43 01](https://github.com/ShipStream/ups-rest-php-sdk/assets/149160420/f3d11cf7-cfa6-43bf-9605-8ecdc3dfdc44)

**Comment by elidrissidev** [comment]
That's the problem, the UPS API expects the `ShipmentCharge` field to be an array of objects, if you have only one charge object then just pass it as the only value like this:

```php
$paymentInformation = new \ShipStream\Ups\Api\Model\ShipmentPaymentInformation();
$transportationCharge = new \ShipStream\Ups\Api\Model\PaymentInformationShipmentCharge();
$transportationCharge->setType('01');
// ...
$charges = [$transporationCharge];
$paymentInformation->setShipmentCharge($charges);
```
