### ISSUE TITLE
Paperless wrong documentID type

### ISSUE THREAD

**Issue by heckleberry** [ShipStream/ups-rest-php-sdk#17]
Hello,
Thanks for sharing your library.

I have an issue calling the "paperlessdocuments/v1/upload" endpoint
Seems like your library is using the wrong type for the value "DocumentId" to denormalize the response, "string" instead of "array"
- vendor/shipstream/ups-rest-php-sdk/src/Api/Normalizer/UploadResponseFormsHistoryDocumentIDNormalizer.php
- UploadResponseFormsHistoryDocumentID

 function : setDocumentID(string $documentID)
Here is the error :
TypeError: Argument 1 passed to ShipStream\Ups\Api\Model\UploadResponseFormsHistoryDocumentID::setDocumentID() must be of the type string, array given
But UPS send an array (as is it said in the UPS documentation) :
```
"FormsHistoryDocumentID": {
            "DocumentID": [
                "2013-12-04-00.15.33.207814"
            ]
        }
```
Thanks, Michel.

**Comment by elidrissidev** [comment]
Hey, thanks for the report!

Yeah it seems UPS updated their API specs recently, I'll have a fix ready soon.

**Comment by heckleberry** [comment]
Thanks,
I keep an eye on it then ;)
