### ISSUE TITLE
Error in the Model DimentionsUnitOfMeasurement

### ISSUE THREAD

**Issue by heckleberry** [ShipStream/ups-rest-php-sdk#2]
Hello,
Thanks for your work.

The entity DimentionsUnitOfMeasurement should have 2 values :
- description
- code
But the value "code" is misprint with "unitOfMeasurement"

I did the fix in my local and it works.
I also had to update the file : DimentionsUnitOfMeasurementNormalizer
Same error in this file.

The correct json should be :
"UnitOfMeasurement": {
  "Code": "CM",
  "Description": ""
}
and today we have :
"UnitOfMeasurement": {
  "UnitOfMeasurement": "CM",
  "Description": ""
}

One advice, it can also be good to display the ups error :
Today we have :
ShipStream\Ups\Api\Exception\ShipmentBadRequestException: Invalid Request

The UPS error : 
Missing dimensions unit of measurement code for package 1.

Best Regards, Michel.

**Comment by elidrissidev** [comment]
Hey, thanks for the report.

You're right, it seems UPS updated their API definitions recently, I will push a fix shortly.

> One advice, it can also be good to display the ups error :
Today we have :
ShipStream\Ups\Api\Exception\ShipmentBadRequestException: Invalid Request

The full error message(s) can be read using the caught exception object (depending on the endpoint schema), as I believe by default `$e->getMessage()` only contains the status code description. Example:
```php
$errors = $e->getErrorResponse()->getResponse()->getErrors();
$errors = array_map(fn($error) => $error->getMessage(), $errors);
echo 'Error: '.implode(' - ', $errors)."\n";
```
