### ISSUE TITLE
ShipmentCharge is missing in the PaymentInformation parameter of the shipment method

### ISSUE THREAD

**Issue by jsrgqinbin** [ShipStream/ups-rest-php-sdk#5]
ShipmentCharge is missing in the PaymentInformation parameter of the shipment method

**Comment by elidrissidev** [comment]
Please make sure you use the correct model which is [`ShipmentPaymentInformation`](https://github.com/ShipStream/ups-rest-php-sdk/blob/main/src/Api/Model/ShipmentPaymentInformation.php). The `PaymentInformation` model is to be used with the Tracking API and has different fields.
