### ISSUE TITLE
Broken against latest symfony/serializer

### ISSUE THREAD

**Issue by staticglobal** [ShipStream/ups-rest-php-sdk#9]
Tried adding this package to a Laravel-10 project running on PHP-8.3 and immediately got this:

```
PHP Fatal error:  Declaration of ShipStream\Ups\Api\Normalizer\JaneObjectNormalizer::denormalize($data, $class, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Normalizer\DenormalizerInterface::denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed in /path/to/my/vendor/shipstream/ups-rest-php-sdk/src/Api/Normalizer/JaneObjectNormalizer.php on line 40
```

I saw you recently dropped your explicit composer dependency on `symfony/serializer` "to allow installing on PHP 8.x", but I don't think it is that simple. If your code is not compatible with the latest versions of `symfony/serializer` you should declare the maximum version you are compatible with. Otherwise you should make your code that extends/implements these interfaces compatible with the latest.

**Comment by colinmollenhour** [comment]
@elidrissidev Perhaps we need to maintain a fork that is compatible with PHP 7.4 until it is no longer needed and let the main branch be compatible with 8.0+?

**Comment by elidrissidev** [comment]
I dug more into this and it seems there's no way to support both versions simultaneously. I also noticed that jane v7.4.0 added support for `symfony/serializer` v7 but they also dropped support for PHP 7 😕.

@colinmollenhour What do you think about tagging a new major version in `main` with PHP 8 support, and maintaining v1 in a branch called `1.x` for PHP 7 support?
